name: Rust

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Simple check
      run: cargo check --verbose
    - name: Check feature metrics
      run: cargo check --features metrics --verbose
    - name: Check feature optimizer
      run: cargo check --features optimizer --verbose

    - name: Install font for draws feature
      run: sudo apt install -y libfontconfig1-dev

    - name: Check feature draws
      run: cargo check --features draws --verbose
    - name: Check feature draws and metrics
      run: cargo check --features draws,metrics --verbose


    - name: Run simple test
      run: cargo test --verbose
    - name: Test feature metrics
      run: cargo test --features metrics --verbose
    - name: Test feature optimizer
      run: cargo test --features optimizer --verbose
    - name: Test feature draws
      run: cargo test --features draws --verbose
    - name: Test feature draws and metrics
      run: cargo test --features draws,metrics --verbose