name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Build serde
      run: cargo build --features serde --verbose
    - name: Build metric
      run: cargo build --features metrics --verbose
    - name: Build optimizer
      run: cargo build --features optimizer --verbose
    - name: Build all
      run: cargo build --all-features --verbose
    
    - name: Install wasm32 target
      run: rustup target add wasm32-unknown-unknown
    
    - name: Build wasm
      run: cargo build --target=wasm32-unknown-unknown --verbose
    - name: Build wasm all
      run: cargo build --target=wasm32-unknown-unknown --all-features --verbose
    
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests all
      run: cargo test --all-features --verbose
